In [4]:
#Import necessery libraries
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
#Load dataset
df=pd.read_csv('../Data/ontario_retirement_house_investment_data.csv')

df.head(5)

,Date,City,Property_Price,Occupancy_Rate,Inflation_Rate,Population_Age_65+,Population_Age_65_Growth,Median_Age,Income_Level,Proximity_to_Healthcare,Walkability_Score,Crime_Rate,Property_Tax_Rate,Public_Transport_Access,Government_Incentives,Environmental_Quality,Senior_Living_Vacancy_Rate,Mental_Health_Programs,Memory_Care_Availability
0,2010-01-01,Toronto,949671,88,2.80,48617,0.97,42,83688,1,89,8,1,0,0,72.169690,10.247564,1,0
1,2010-02-01,Toronto,976743,85,1.42,40920,1.87,48,38815,3,71,6,1,1,0,62.602064,14.488855,1,1
2,2010-03-01,Toronto,839936,87,2.32,47083,0.87,45,72338,4,71,6,1,1,1,97.579958,13.948274,1,1
3,2010-04-01,Toronto,777916,72,1.59,48844,1.67,43,55483,8,64,4,2,0,1,62.982026,14.868869,1,0
4,2010-05-01,Toronto,1003100,89,1.22,59313,1.58,41,64969,4,53,4,1,1,1,95.488510,9.722149,0,1

In [26]:
# Get summary statistics of the dataset
df.describe()

,Property_Price,Occupancy_Rate,Inflation_Rate,Population_Age_65+,Population_Age_65_Growth,Median_Age,Income_Level,Proximity_to_Healthcare,Walkability_Score,Crime_Rate,Property_Tax_Rate,Public_Transport_Access,Government_Incentives,Environmental_Quality,Senior_Living_Vacancy_Rate,Mental_Health_Programs,Memory_Care_Availability
count,1.680000e+03,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000
mean,9.025838e+05,82.466667,2.524089,50458.847619,1.987280,45.015476,59987.467857,5.415476,69.992857,5.499405,1.497024,0.707143,0.606548,80.006713,9.847344,0.623214,0.705952
std,9.961713e+04,7.285472,0.865969,9861.390971,0.850299,2.940911,14960.494435,2.593803,11.525405,2.575136,0.500140,0.455209,0.488661,11.578223,2.862708,0.484725,0.455749
min,6.000000e+05,70.000000,1.000000,17587.000000,0.500000,40.000000,12011.000000,1.000000,50.000000,1.000000,1.000000,0.000000,0.000000,60.010098,5.000481,0.000000,0.000000
25%,8.340052e+05,76.000000,1.780000,43928.500000,1.270000,43.000000,49388.750000,3.000000,60.000000,3.000000,1.000000,0.000000,0.000000,70.139384,7.299857,0.000000,0.000000
50%,9.016830e+05,82.000000,2.530000,50184.000000,1.960000,45.000000,59907.000000,5.000000,70.000000,5.500000,1.000000,1.000000,1.000000,80.179153,9.838966,1.000000,1.000000
75%,9.713042e+05,89.000000,3.270000,57075.000000,2.710000,48.000000,70089.000000,8.000000,80.000000,8.000000,2.000000,1.000000,1.000000,89.813780,12.219370,1.000000,1.000000
max,1.200000e+06,95.000000,4.000000,94791.000000,3.500000,50.000000,110661.000000,10.000000,90.000000,10.000000,2.000000,1.000000,1.000000,99.968292,14.994591,1.000000,1.000000

In [27]:
df.isnull().sum()

Date                          0
City                          0
Property_Price                0
Occupancy_Rate                0
Inflation_Rate                0
Population_Age_65+            0
Population_Age_65_Growth      0
Median_Age                    0
Income_Level                  0
Proximity_to_Healthcare       0
Walkability_Score             0
Crime_Rate                    0
Property_Tax_Rate             0
Public_Transport_Access       0
Government_Incentives         0
Environmental_Quality         0
Senior_Living_Vacancy_Rate    0
Mental_Health_Programs        0
Memory_Care_Availability      0
dtype: int64